# Generated by Django 2.0.4 on 2022-06-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0007_auto_20220606_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='campo_teste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
